### ISSUE TITLE
Get recommendation from PureSVD model given user's preference

### ISSUE THREAD

**Issue by wahyudierwin** [evfro/polara#12]
Hi @evfro ,

I want to get recommendation based on user's preference, not user_id. For example, there are 10 items in training data, and (new) user's preference is `[0,1,0,0,0,0,1,1,0,0]`. Theoretically, we just multiply the vector and item matrix (`p . V . Vt`). How can I achieve that?

**Comment by wahyudierwin** [comment]
I see the function to get recommendation is in https://github.com/evfro/polara/blob/master/polara/recommender/models.py#L320. However, if I pass list of string as `user_info`, it will return `ValueError: too many values to unpack (expected 2)` and not go into exception.

**Comment by HLGFCGCG** [comment]
@wahyudierwin I'm facing the same issue. Were you able to get it to work?

**Comment by wahyudierwin** [comment]
@HLGFCGCG yes, I manually map from string id into integer id.

**Comment by evfro** [comment]
@wahyudierwin @HLGFCGCG hi, thanks for the report! There was a bug with how different input formats are handled, which only appear in certain cases. It's fixed now. Please, update polara (you can use either develop or master branch, as they are currently identical).

**Comment by evfro** [comment]
@wahyudierwin apart from the issue, please, note that input with duplicate entries like [0, 0, 1, 1, 2, 2] is invalid. Internally, it will be converted into [0, 1, 2] but the feedback will be increased according to the number of repeats. E.g., for implicit case the feedback vector will become [2, 2, 2] instead of [1, 1, 1]. In your example, it will become [7, 3] as `0` is repeated 7 times and `1` - 3 times.
In the case of explicit feedback (e.g., ratings), the feedback values will be multiplied, e.g. if item `A` has rating 5 and occurs 3 times in the input, the feedback for this item will become 3x5=15.

**Comment by wahyudierwin** [comment]
@evfro Thanks for the update! I will try the updated version later.

About the user's preference, what I wrote `[0,1,0,0,0,0,1,1,0,0]` means that the user likes the 2nd, 7th, and 8th items (1-based indexing), not the user likes 1st item multiple times. I hope it is clear.

**Comment by evfro** [comment]
@wahyudierwin I see now. OK, in that case what you need to submit as input is a list of liked items. Here's a simple example:

```python
data = pd.DataFrame([
        ('u1', 'Matrix'),
        ('u3', 'Matrix'),
        ('u2', 'GF'),
        ('u1', 'LOTR'),
        ('u3', 'LOTR'),
        ('u2', 'SW1'),
        ('u3', 'SW4'),
    ], columns=['userid', 'itemid'])

dm = RecommenderData(data 'userid', 'itemid')
dm.prepare_training_only()

svd = SVDModel(dm)
svd.rank = 2
svd.build()

svd.show_recommendations(['LOTR', 'Matrix'], topk=3)
```
Note `show_recommendations` is made to explicitly work with external item representation, not an internal (numeric) index that polara uses for all other computations (look at `dm.index.itemid` to see the difference).

**Comment by wahyudierwin** [comment]
@evfro Got it, that's what I'm looking for. I greatly appreciate that.
