### ISSUE TITLE
polara.preprocessing module not found

### ISSUE THREAD

**Issue by KristinaLifirenko** [evfro/polara#14]
Hi! I clone a git repository with polara and run setup.py in appropriate folder. But then trying to import it got a ModuleNotFoundError: No module named 'polara.preprocessing'. 
Is there some hints to use it or it's a bug?

**Comment by evfro** [comment]
@KristinaLifirenko disregard previous comment, it was a bug (missing init file). Fixed now. Please, run installation once again. It should be fine now. Also note there's a simpler way to install directly from source (see update installation section of readme).

**Comment by KristinaLifirenko** [comment]
@evfro thanks a lot for fast reaction. I tryed it once again and got missing hybrid package now:
![image](https://user-images.githubusercontent.com/58210448/104796082-903c2780-57c4-11eb-8419-3dafbaf91353.png)

**Comment by evfro** [comment]
@KristinaLifirenko  thanks for the report! The entire problem was due to my inappropriate use of implicit namespace. Fixed now. New hotfix version is released, please, update. Everything should import fine now.

**Comment by KristinaLifirenko** [comment]
@evfro yes, now it's fine, thanks! Will continue explore you excellent tool=)
