### ISSUE TITLE
Precision@K

### ISSUE THREAD

**Issue by dKustura** [Evfro/polara#5]
I am currently working with an implicit feedback dataset and trying to evaluate a model based on the precision@K measure. I am having difficulties understanding the implemented precision calculation in a case when the list of recommendations consists only of top K recommendations. 

@Evfro Can you please clarify if the calculated precision is a precision@K or a regular precision measure?

**Comment by Evfro** [comment]
Hi.

Yes, currently, all metrics are evaluated **@ K, which is by default set to 10**. There are several ways to control the value of K in Polara.

* You can specify K individually for each recommender model by setting the `topk` attribute, e.g.
```python
model.topk = <your value>
```
* Alternatively, you can globally redefine the default value of K for current session via the `defaults` module (make sure to do that before creating any recommender model!):
```python
from polara.recommender import defaults
defaults.topk = <your value>
```

* Finally, you can also provide the value of K at the evaluation time:
```python
model.evaluate(topk=<your value>)
```
Note that if you have already generated recommendations with some old value of K (e.g., by accessing the `.recommendations` attribute of the model or by calling `model.evaluate()`) and decided to change it to a new value K' > K, then recommendations will be automatically recomputed. Conversely, for K' < K the recommendations list will be simply truncated without any recomputations.

Also note that you can automate running experiments for different values of K via Polara's pipelines, especially using the `topk_test` method, as shown in [this tutorial](https://nbviewer.jupyter.org/github/evfro/polara/blob/master/examples/Example_ML1M.ipynb#Run-experiments).
