### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'item_features'

### ISSUE THREAD

**Issue by bhanga-manish** [evfro/polara#8]
Referring this blogs code https://www.eigentheories.com/blog/lightfm-vs-hybridsvd/
The class ItemColdStartData has attribute item_features.
which is removed in the current version of the package.

Is their another way to add item features in the data model or the code behaves the same without it.

**Comment by evfro** [comment]
Sorry for confusion. This is not removed, it hasn't been commited to the release version yet. In order to run this code you have to install polara from the `develop` branch. Run
`pip install --upgrade git+https://github.com/evfro/polara.git@develop#egg=polara`

**Comment by bhanga-manish** [comment]
Thanks
I'll check

**Comment by bhanga-manish** [comment]
This is working, Thanks.
